browser=chrome
tutorialNinjaApplication= http://tutorialsninja.com/demo
firstName = rakesh
lastName = Umale
emailID = rakeshUmale4@yop.com
newEmailID = rakesUmale34@yop.com
contactNo = 7218688193
password = Ramesh@605

#Test Data excel sheet path
testDataSheet_Path = C:\\Users\\2110883\\OneDrive - Cognizant\\Desktop\\ninjaWeb_Automation\\ninjaTutirial_CompleteProject\\project_code\\src\\main\\resources\\TestDataSheet.xlsx
#registration_customer_query=select * from registration_userDetails where emailID ='raghubadarkhe09@yopmail.com' ;
#validCredential_query=select * from customer_credentialDetails WHERE validation_status = 'valid';
#invalidCredential_query=select * from customer_credentialDetails WHERE validation_status = 'invalid';

//Login functionality
loginCredential_email = pavanhiware11@gmail.com
loginCredential_password = Hiware1234
loginInvalid_password = 1234
changePassword_newPassword = Hiware1234
